/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package logs;

import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ironm
 */
public class VisualLogs extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VisualLogs.class.getName());

    private FileManager fm = new FileManager();
    private Gestore gestore = new Gestore();
    private List<String[]> dati;

    /**
     * Creates new form VisualLogs
     */
    public VisualLogs() {
        initComponents();
    }

    /**
     * aggiorna il contenuto della tabella con i dati forniti.
     *
     * * @param listaDati lista di array di stringhe.
     */
    
    private void aggiornaTabella(List<String[]> listaDati, String[] colonne) {
        
        DefaultTableModel modello = new DefaultTableModel(colonne, 0);
        for (String[] riga : listaDati) {
            modello.addRow(riga);
        }
        jTable2.setModel(modello);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnCarica = new javax.swing.JButton();
        btnIpSospetti = new javax.swing.JButton();
        btnAccessiFalliti = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setName("jTable1"); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        btnCarica.setText("Carica  i dati");
        btnCarica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaricaActionPerformed(evt);
            }
        });

        btnIpSospetti.setText("Ip sospetti");
        btnIpSospetti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIpSospettiActionPerformed(evt);
            }
        });

        btnAccessiFalliti.setText("AccessiFalliti");
        btnAccessiFalliti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccessiFallitiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCarica)
                    .addComponent(btnIpSospetti)
                    .addComponent(btnAccessiFalliti))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAccessiFalliti, btnCarica, btnIpSospetti});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(btnCarica)
                .addGap(18, 18, 18)
                .addComponent(btnIpSospetti)
                .addGap(18, 18, 18)
                .addComponent(btnAccessiFalliti)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCarica.getAccessibleContext().setAccessibleName("btn");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCaricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaricaActionPerformed

        dati = fm.leggiFile();
        
            String[] colLog = {"Timestamp", "Utente", "IP", "Stato"};
            aggiornaTabella(fm.leggiFile(), colLog); 
    }//GEN-LAST:event_btnCaricaActionPerformed

    private void btnAccessiFallitiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccessiFallitiActionPerformed

            String[] colUtenti = {"Nome Utente", "Totale Fallimenti"};
            List<String[]> datiFiltrati = gestore.accessiFalliti(dati);
            aggiornaTabella(datiFiltrati, colUtenti);
    }//GEN-LAST:event_btnAccessiFallitiActionPerformed

    private void btnIpSospettiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIpSospettiActionPerformed
        
            String[] colIp = {"Indirizzo IP", "Conteggio FAIL"};
            List<String[]> datiFiltrati = gestore.ipSospetti(dati);
            aggiornaTabella(datiFiltrati, colIp);
    }//GEN-LAST:event_btnIpSospettiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VisualLogs().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccessiFalliti;
    private javax.swing.JButton btnCarica;
    private javax.swing.JButton btnIpSospetti;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
